### PR TITLE
Make sure this works in multi memcache nodes environment. 

### PR DESCRIPTION
**Pull request by tuanmh**

### CODE REVIEW

**Comment by cmmarslender** [comment]
Ran into this issue today on a site using 2 memcached nodes. Verified the fix resolved the issue for me. However, I believe it needs to be updated to return `$retData`, not `$data`.

**Comment by rmccue** [comment]
@cmmarslender That makes sense to me. Do you want to open a new PR with that change, and I'll bug @joehoyle about getting it reviewed? :)

**Comment by cmmarslender** [comment]
@rmccue Opened #9

**Comment by tuanmh** [comment]
> Ran into this issue today on a site using 2 memcached nodes. Verified the fix resolved the issue for me. However, I believe it needs to be updated to return $retData, not $data.

Ah right, I forgot to push that change, our production code is actually returning `$retData` and confirm it works great.

**Comment by joehoyle** [comment]
Closing in favor of https://github.com/humanmade/wordpress-pecl-memcached-object-cache/pull/9, thanks for putting this together, sorry you are not in the tree!

**Pull request closed without merging**
